#ifndef PUTITONICE_LIB_UI_GLOBAL_H
#define PUTITONICE_LIB_UI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PUTITONICE_LIB_UI_LIBRARY)
#  define PUTITONICE_LIB_UISHARED_EXPORT Q_DECL_EXPORT
#else
#  define PUTITONICE_LIB_UISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PUTITONICE_LIB_UI_GLOBAL_H
