#ifndef PUTITONICE_LIB_ICE_GLOBAL_H
#define PUTITONICE_LIB_ICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PUTITONICE_LIB_ICE_LIBRARY)
#  define PUTITONICE_LIB_ICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define PUTITONICE_LIB_ICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PUTITONICE_LIB_ICE_GLOBAL_H
